### ISSUE TITLE
lowopt_ settings

### ISSUE THREAD

**Issue by g8dhe** [PiInTheSky/lora-gateway#25] opened 2016-09-03 12:32 UTC
Doesn't appear to function any Y/N/0/1 makes no difference.

**Comment by dbrooke** [comment] 2016-09-03 12:52
Assuming that the problem is that it can't be disabled if a mode setting has already enabled it then I suspect this may be https://github.com/PiInTheSky/lora-gateway/pull/11 which is probably work in progress as the request has been closed but the changes have not yet appeared in the master branch

**Comment by daveake** [comment] 2016-09-03 13:17
I'll check this later.  Might have got lost in the merge.

**Comment by daveake** [comment] 2016-09-14 09:55
Turns out it wasn't fixed; my bad.

Fixed in V1.8.2 which is up down; V1.8.3 coming later today.

**Closed** 2018-02-12 14:09 UTC
